services:
  swag:
    #
    # a reverse proxy to expose the hapi server
    # complete snapshot of all configs found at gs://hapi-vm/opt/appdata
    # see /opt/appdata/swag/config/nginx/ for proxy configuration
    #
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=$DOMAIN
      - VALIDATION=http
      - SUBDOMAINS=docs,google-fhir #optional
      # - CERTPROVIDER= #optional
      # - DNSPLUGIN=cloudflare #optional
      # - PROPAGATION= #optional
      # - EMAIL= #optional
      # - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=$EXTRA_DOMAINS
      - STAGING=${STAGING:-false} # optional
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  google-fhir:
    image: google-fhir
    container_name: google-fhir
    ports:
      # (HOST:CONTAINER),
      - "8090:8080" 
    environment:
      - FHIR_SERVICE_URL=${FHIR_SERVICE_URL}
